branches:
  only:
    - master

language: go

go:
  - 1.8

install:
  - go get -t ./...
  - go get -u github.com/kisielk/errcheck

script:
  - go test ./...
  - errcheck ./...
  - |
    go run main.go -cluster ./util/cluster_test.json &
    sleep 2
  - go run integtests/main.go
  - python pyclient/integtest.py
