language: go

install:
  - go get -t ./...
  - go get -u github.com/kisielk/errcheck

script:
  - go test ./...
  - errcheck ./...
  - |
    go run main.go &
    sleep 2
    python pyclient/integtest.py
