branches:
  only:
    - master

language: go

install:
  - go get -t ./...
  - go get -u github.com/kisielk/errcheck
  - sudo pip install grpcio # FIXME: use pipenv install

script:
  - go test ./...
  - errcheck ./...
  - |
    go run main.go &
    sleep 2
    python pyclient/integtest.py
